"""
Abstract base classes and interfaces for DecisionOS Machine Learning and AI Decision Engine.
Supports modular extensions in subsequent phases (Auto-ML, Prophet Forecasting, Anomaly Detection).
"""
import abc
from dataclasses import dataclass, field
from enum import Enum
from typing import Any, Dict, List, Optional

import pandas as pd


class MLTaskType(str, Enum):
    """Supported automated machine learning task classifications."""
    REGRESSION = "regression"
    CLASSIFICATION = "classification"
    FORECASTING = "forecasting"
    ANOMALY_DETECTION = "anomaly_detection"
    CLUSTERING = "clustering"
    RECOMMENDATION = "recommendation"


@dataclass
class PredictionResult:
    """Standardized prediction output payload from any ML model."""
    task_type: MLTaskType
    predictions: List[Any]
    confidence_scores: List[float] = field(default_factory=list)
    feature_importances: Dict[str, float] = field(default_factory=dict)
    metrics: Dict[str, float] = field(default_factory=dict)
    shap_values: Optional[List[Dict[str, float]]] = None


@dataclass
class RecommendationItem:
    """Actionable AI business recommendation generated by the Decision Engine."""
    title: str
    description: str
    confidence_score: float
    impact_area: str  # e.g., "Revenue", "Inventory", "Churn", "Marketing"
    suggested_action: str
    supporting_metrics: Dict[str, Any] = field(default_factory=dict)


class BaseInferenceEngine(abc.ABC):
    """Abstract interface for all supervised and unsupervised ML inference engines."""

    @abc.abstractmethod
    def fit(self, df: pd.DataFrame, target_column: Optional[str] = None) -> "BaseInferenceEngine":
        """Train or fit the model on a cleaned DataFrame."""
        pass

    @abc.abstractmethod
    def predict(self, df: pd.DataFrame) -> PredictionResult:
        """Run inference and return structured prediction results with confidence."""
        pass


class BaseAutoMLPipeline(abc.ABC):
    """Abstract interface for automated ML task detection and model selection."""

    @abc.abstractmethod
    def detect_task_type(self, df: pd.DataFrame, target_column: str) -> MLTaskType:
        """Analyze dataset target column and determine appropriate ML task."""
        pass

    @abc.abstractmethod
    def train_best_model(self, df: pd.DataFrame, target_column: str) -> BaseInferenceEngine:
        """Train candidate models (XGBoost, LightGBM, RandomForest) and return top performer."""
        pass


class BaseAIDecisionProvider(abc.ABC):
    """Abstract interface for LLM + RAG business recommendation generation."""

    @abc.abstractmethod
    async def generate_recommendations(
        self,
        dataset_summary: Dict[str, Any],
        ml_insights: Optional[PredictionResult] = None,
    ) -> List[RecommendationItem]:
        """Synthesize dataset summaries and ML metrics into actionable business recommendations."""
        pass
